### ISSUE TITLE
Allow custom section names in hoc files for Cell object

### ISSUE THREAD

**Issue by darshanmandge** [BlueBrain/BlueCelluLab#140]
Hi,
The Cell object intialisation does not support hoc files with custom section names:

```
bluecellulab/psection.py:89, in PSection.__init__(self, hsection, isec)
     87     self.section_type = 'myelin'
     88 else:
---> 89     raise Exception(
     90         "PSection: Section of unknown type: %s" %
     91         self.name)
     93 self.psegments: list[PSegment] = []
     94 self.maxsegdiam = 0.0

Exception: PSection: Section of unknown type: MOBopl_mTC_bSTUT_bluecellulab_0x7fff01743ad0[0].hillock
```

**Comment by AurelienJaquier** [comment]
It looks like we did not have this problem with 1.8.4

**Comment by anilbey** [comment]
The section types have always been strict, they even affect the NEURONs random number generation process. To my knowledge BCL or Neurodamus have never supported section types other than `somatic, basal, apical, axonal, myelin`.

In 1.8.4 if it works without any errors, it points to some problems. 

E.g. this method below might not be executed:
https://github.com/BlueBrain/BlueCelluLab/blob/edfb2663d33d8e277b28a5aa764b1627bfc80c82/bluecellulab/cell/core.py#L177

**Comment by anilbey** [comment]
Fixed in https://github.com/BlueBrain/BlueCelluLab/pull/167.
