### ISSUE TITLE
Warning needed on serialised sections? 

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/BlueCelluLab#176]
This warning 

```
BlueCelluLab/bluecellulab/cell/serialized_sections.py:40: UserWarning: [Warning] SerializedSections: v(0.0001) < 0. index=1 v()=-65.0
```

is a pain when we use non-bbp mod files, is it really necessary to have it always printed, not in debug mode or so?

**Comment by anilbey** [comment]
Thanks, this is a very useful feedback - using bluecellulab with non-bbp mod files. Sounds good it can be printed in debug mode and can be set to be ignored. Do you want to make the PR or shall I do that?

**Comment by arnaudon** [comment]
do as you want!
