### ISSUE TITLE
StimulusFactory: enable amplitude based versions of the protocols

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/BlueCelluLab#180]
At the moment the following protocols are only threshold-based.
* neg_cheops
* pos_cheops
* fire_pattern
* iv
* idrest
* ap_waveform

Some of the non-bbp models however are amplitude based.

The StimulusFactory should be extended to support the amplitude based methods as well.
The amplitude based implementation can be reused by the threshold based implementation.

Such as the following:
https://github.com/BlueBrain/BlueCelluLab/blob/fcf8ad0727c93b3480736c43cef0333eaa4bd14e/bluecellulab/stimulus/factory.py#L264-L272

**Comment by stefanoantonel** [comment]
Cool thanks!!
