### ISSUE TITLE
Bug: `matplotlib>=3.9` - module 'matplotlib.cm' has no attribute 'get_cmap'

### ISSUE THREAD

**Issue by joni-herttuainen** [BlueBrain/BlueCelluLab#183]
Matplotlib introduced [breaking changes in version 3.9](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#removals), which also causes bluecellulab to crash:
```
<Truncated traceback>
...
File ".../venv/lib/python3.11/site-packages/bluecellulab/psegment.py", line 38, in __init__
    self.color_map = cm.get_cmap("hot")
                     ^^^^^^^^^^^
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```

**Comment by ilkilic** [comment]
Thank you @joni-herttuainen for raising this issue. PR #184 addresses it by replacing `get_cmap` with `colormaps`

**Comment by joni-herttuainen** [comment]
Since this issue is fixed, I'll close it. Thanks for a quick response.
