### ISSUE TITLE
broken link in the examples README file

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/BlueCelluLab#207]
It is here
https://github.com/BlueBrain/BlueCelluLab/blob/main/examples/README.rst

There is a typo in here in the word "Stimulation"

```markdown
   * - `Multiple-protocols.ipynb <7-Extra-Simutlation/Multiple-protocols.ipynb>`_
     - Simulating multiple protocols on a cell using previous examples

```

404 - page not found
The 

main
 branch of 

BlueCelluLab
 does not contain the path 

examples/7-Extra-Simutlation/Multiple-protocols.ipynb.

**Comment by ilkilic** [comment]
fixed in https://github.com/BlueBrain/BlueCelluLab/pull/208
