### ISSUE TITLE
during import, some neuron function returns 1 check if it is something important

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/BlueCelluLab#4]
The result 1 gets printed to the console. Although it's harmless, handling it can be beneficial.

Assuming that in this function's context, 1 signifies success and 0 indicates failure, it would be beneficial to handle the failure scenario within Python. This adjustment would spare users from deciphering potentially confusing error messages coming from the C/C++ implementation.

**Comment by anilbey** [comment]
`bluecellulab/hoc/Cell.hoc` is causing it

**Comment by arnaudon** [comment]
Ah very good catch, I get a lot of these! @eleftherioszisis  as well ;)

**Comment by anilbey** [comment]
Duly noted. I will give priority to this.
 Just to better understand the case: are you running bluecellulab in multiple processes? Or is it giving a lot of those on a single process?

**Comment by anilbey** [comment]
I couldn't locate the exact line causing it since I couldn't place a breakpoint on that hoc file (Cell.hoc).

**Comment by anilbey** [comment]
Closing since it's fixed with #148.
